import { database, mailConfig } from '@/lib/server-db';
import { scoreDiagnostic } from '@/lib/diagnostic';
import { courses, ORIGIN } from '@/lib/content';
export async function POST(req:Request){
 if(req.headers.get('origin')!==new URL(req.url).origin)return Response.json({error:'Please submit this form from the website.'},{status:403});
 if(!req.headers.get('content-type')?.includes('application/json'))return Response.json({error:'Please submit the website form.'},{status:415});
 try{const raw=await req.text();if(raw.length>12000)return Response.json({error:'Your message is too long.'},{status:413});const p=JSON.parse(raw);if(p.website)return Response.json({error:'Please leave the hidden field empty.'},{status:400});
 const str=(k:string,max:number)=>typeof p[k]==='string'?p[k].trim().slice(0,max):'';
 const email=str('email',254).toLowerCase(),kind=str('kind',10),name=str('name',120),timezone=str('timezone',100),availability=str('availability',200);
 if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||p.consent!==true||!['trial','report'].includes(kind))return Response.json({error:'Add a valid email and confirm permission to handle your request.'},{status:400});
 if(kind==='trial'&&(!name||!timezone||!availability))return Response.json({error:'Please add your name, time zone and availability.'},{status:400});
 if(kind==='report'&&(!Array.isArray(p.answers)||p.answers.length!==7||!p.answers.every((v:unknown)=>Number.isInteger(v)&&Number(v)>=0&&Number(v)<=2)))return Response.json({error:'Please complete all seven diagnostic questions.'},{status:400});
 const result=kind==='report'?scoreDiagnostic(p.answers):null;const course=result?.course.slug||str('course',80);if(course!=='not-sure'&&!courses.some(c=>c.slug===course))return Response.json({error:'Please choose a valid course.'},{status:400});
 const db=await database(),now=Date.now();const recent=await db.prepare('SELECT id FROM leads WHERE email = ? AND created_at > ? LIMIT 1').bind(email,now-60000).first();if(recent)return Response.json({error:'We received a request from this email just now. Please wait a minute before sending another.'},{status:429});
 const id=crypto.randomUUID(),utm:Record<string,string>={};for(const k of ['utm_source','utm_medium','utm_campaign','utm_term','utm_content'])if(typeof p.utm?.[k]==='string')utm[k]=p.utm[k].slice(0,200);
 await db.prepare('INSERT INTO leads (id,kind,email,name,timezone,availability,message,course,dimension,scores,utm,consent_version,created_at,email_status) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(id,kind,email,name,timezone,availability,str('message',2000),course,result?.dimension.name||null,result?JSON.stringify(result.scores):null,JSON.stringify(utm),'request-only-2026-09-06',now,'pending').run();
 let sent=false;const mail=await mailConfig();if(result&&mail.ready){const text=`Your Beyond Fluency Lab report\n\nYour plateau: ${result.dimension.name}\n\n${result.dimension.description}\n\nYour scenario selections: ${result.scores.join(' / ')} (structure / pressure / register; 6 scenarios). ${result.tied?'There was a tie; your latest relevant scenario selected the starting point.':''}\n\nPractice this week\n${result.dimension.exercise}\n\nA course to consider\n${result.course.name} — ${result.course.duration}, €${result.course.price}. ${p.answers[6]===0?'You chose an interview as your upcoming situation.':result.course.short}\n${ORIGIN}/courses/${result.course.slug}\n\nYour related guide\n${ORIGIN}/blog/${result.dimension.guide}\n\nThis is a self-reflection tool, not a validated assessment. You requested this report; you have not been added to a marketing list.\nPrivacy: ${ORIGIN}/legal/privacy`;
 try{const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${mail.key}`,'Content-Type':'application/json','Idempotency-Key':id},body:JSON.stringify({from:mail.from,to:[email],subject:`Your plateau: ${result.dimension.name}`,text})});sent=response.ok;await db.prepare('UPDATE leads SET email_status = ? WHERE id = ?').bind(sent?'sent':'failed',id).run();}catch{await db.prepare('UPDATE leads SET email_status = ? WHERE id = ?').bind('failed',id).run();}}
 return Response.json({id,message:kind==='trial'?'Your trial request has been saved. Your session is not booked yet; the team will need to confirm a time with you.':sent?'Your personalised report has been sent. Check your inbox and spam folder.':'Your report request has been saved. Email delivery is pending; you can use your full result and guide on this page now.'},{status:201,headers:{'Cache-Control':'no-store'}});
 }catch(e){console.error('Lead request failed',e instanceof Error?e.name:'Unknown');return Response.json({error:'We could not save your request. Your details are still in the form; please try again.'},{status:503});}
}
