'use client';
import { useEffect, useState } from 'react';
import { Carousel, CarouselContent, CarouselItem, type CarouselApi } from '@/components/ui/carousel';
import { LabIcon } from './lab-icon';
import { photos } from '@/lib/editorial';
export function MotionDirector(){
 const [paused,setPaused]=useState(false),[systemReduced,setSystemReduced]=useState(false);
 useEffect(()=>{const preference=matchMedia('(prefers-reduced-motion: reduce)');const apply=()=>{setSystemReduced(preference.matches);let saved=false;try{saved=localStorage.getItem('bfl-motion')==='paused'}catch{}setPaused(preference.matches||saved);};apply();preference.addEventListener('change',apply);return ()=>preference.removeEventListener('change',apply);},[]);
 useEffect(()=>{document.documentElement.dataset.motion=paused?'paused':'active';if(paused)return;const targets=document.querySelectorAll<HTMLElement>('[data-reveal]');const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target);}});},{threshold:.08,rootMargin:'0px 0px 24px 0px'});targets.forEach(el=>{const rect=el.getBoundingClientRect();el.classList.add('reveal-ready');if(rect.top<innerHeight&&rect.bottom>0)el.classList.add('is-visible');else observer.observe(el)});let frame=0;const update=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{const range=document.documentElement.scrollHeight-innerHeight;document.documentElement.style.setProperty('--reading-progress',String(range>0?scrollY/range:0));});};addEventListener('scroll',update,{passive:true});update();return ()=>{observer.disconnect();targets.forEach(el=>el.classList.remove('reveal-ready'));removeEventListener('scroll',update);cancelAnimationFrame(frame)};},[paused]);
 useEffect(()=>{if(paused||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const timers=new Set<ReturnType<typeof setTimeout>>();const ripple=(event:PointerEvent)=>{const target=event.target instanceof Element?event.target.closest<HTMLElement>('.btn,.slide-buttons button'):null;if(!target||target.matches(':disabled'))return;const rect=target.getBoundingClientRect();const el=document.createElement('span');el.className='surface-ripple';el.setAttribute('aria-hidden','true');el.style.setProperty('--ripple-size',Math.hypot(rect.width,rect.height)*2+'px');el.style.setProperty('--ripple-x',event.clientX-rect.left+'px');el.style.setProperty('--ripple-y',event.clientY-rect.top+'px');target.appendChild(el);const timer=setTimeout(()=>{el.remove();timers.delete(timer)},700);timers.add(timer)};document.addEventListener('pointerdown',ripple);return()=>{document.removeEventListener('pointerdown',ripple);timers.forEach(clearTimeout);document.querySelectorAll('.surface-ripple').forEach(el=>el.remove())}},[paused]);
 function toggle(){const value=!paused;setPaused(value);try{localStorage.setItem('bfl-motion',value?'paused':'active')}catch{}}
 return <button className="motion-control" onClick={toggle} disabled={systemReduced} aria-pressed={paused}><LabIcon name={paused?'play':'pause'} size={14}/>{systemReduced?'Reduced motion':paused?'Enable motion':'Pause motion'}</button>
}
const chapters=[
 {number:'01',label:'THE FOUNDATION',title:'It began with the person, not the syllabus.',text:'Learn With Smile has spent 7 years teaching in Kolkata and across India. More than 500 learners form the parent academy’s reported teaching history. Small groups and a teacher who knows you remain central to the work.',photo:photos.listening,link:'/about',linkText:'Where we come from'},
 {number:'02',label:'THE QUESTION',title:'What if fluent was only the beginning?',text:'You can know the language and still struggle to make your judgment visible. Beyond Fluency Lab gives that gap a name: the fluency plateau. The training follows the conversation, from a first attempt to feedback and a sharper second attempt.',photo:photos.mentoring,link:'/our-method',linkText:'How we teach'},
 {number:'03',label:'THE NEXT CHAPTER',title:'For the conversations that cross borders.',text:'The European programme is new. We carry forward the live, small-group approach while focusing on persuasive structure, pressure performance and register control. A new chapter, with an honest account of what came before.',photo:photos.practice,link:'/testimonials',linkText:'Our track record, in context'}
];
export function StoryChapters(){const [api,setApi]=useState<CarouselApi>(),[index,setIndex]=useState(0);useEffect(()=>{if(!api)return;const update=()=>setIndex(api.selectedScrollSnap());api.on('select',update);return ()=>{api.off('select',update)};},[api]);return <section className="story-section" aria-labelledby="story-title"><div className="wrap"><div className="section-head" data-reveal><div><p className="eyebrow"><LabIcon name="story" size={18}/>OUR STORY, IN THREE CHAPTERS</p><h2 id="story-title">Experience gives<br/>the work its depth.</h2></div><p>Seven years of teaching.<br/>A considered next chapter.</p></div><Carousel setApi={setApi} opts={{loop:false,align:'start'}} className="story-carousel" aria-label="The Beyond Fluency Lab story"><CarouselContent>{chapters.map((c,i)=><CarouselItem key={c.number} aria-label={'Chapter '+c.number+' of 3'}><div className="story-slide"><figure className="story-image"><img src={c.photo.src} alt={c.photo.alt} width="1400" height="950" loading="lazy"/><figcaption>{c.photo.caption}</figcaption></figure><div className="story-copy"><div className="chapter-line"><span className="chapter-number">{c.number}</span><span>{c.label}</span></div><h3>{c.title}</h3><p>{c.text}</p><a className="text-link" href={c.link} tabIndex={i===index?0:-1}>{c.linkText}<LabIcon name="arrow" size={18}/></a></div></div></CarouselItem>)}</CarouselContent><div className="story-controls"><div className="chapter-select" aria-label="Choose story chapter">{chapters.map((c,i)=><button key={c.number} onClick={()=>api?.scrollTo(i)} aria-current={i===index?'step':undefined} aria-label={'Read chapter '+c.number}><span>{c.number}</span><i/></button>)}</div><p className="sr-only" aria-live="polite">Chapter {index+1} of 3</p><div className="slide-buttons"><button onClick={()=>api?.scrollPrev()} disabled={index===0} aria-label="Previous chapter"><LabIcon name="back"/></button><button onClick={()=>api?.scrollNext()} disabled={index===2} aria-label="Next chapter"><LabIcon name="next"/></button></div></div></Carousel></div></section>}
