'use client';
import { CourseInvitation } from './course-invitation';
import { LabIcon } from './lab-icon';
import { useEffect, useState, useRef } from 'react';
import { courses, ORIGIN } from '@/lib/content';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { Progress } from '@/components/ui/progress';
import { Checkbox } from '@/components/ui/checkbox';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { questions, dimensions, scoreDiagnostic } from '@/lib/diagnostic';
const utmKeys=['utm_source','utm_medium','utm_campaign','utm_term','utm_content'];
function attribution(){return Object.fromEntries(utmKeys.map(k=>[k,new URLSearchParams(window.location.search).get(k)?.slice(0,200)||'']).filter(x=>x[1]));}
export function LeadForm({report,answers,enrol=false}:{report?:ReturnType<typeof scoreDiagnostic>,answers?:number[],enrol?:boolean}){
 const [busy,setBusy]=useState(false),[status,setStatus]=useState(''),[error,setError]=useState(false),[consent,setConsent]=useState(false),[emailReady,setEmailReady]=useState(false),[storageReady,setStorageReady]=useState(false),[course,setCourse]=useState(report?.course.slug||'not-sure');
 useEffect(()=>{fetch('/api/config').then(r=>r.json()).then(raw=>{const x=raw as {emailReady?:boolean;storageReady?:boolean};setEmailReady(Boolean(x.emailReady));setStorageReady(Boolean(x.storageReady))}).catch(()=>{});if(!report){const c=new URLSearchParams(location.search).get('course');if(courses.some(x=>x.slug===c))setCourse(c!);}},[report]);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!consent){setError(true);setStatus('Please confirm that we may use your details for this request.');return;}setBusy(true);setStatus('');const f=new FormData(e.currentTarget);try{const r=await fetch('/api/leads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:report?'report':enrol?'enrolment':'trial',email:f.get('email'),name:f.get('name')||'',timezone:f.get('timezone')||'',availability:f.get('availability')||'',message:f.get('message')||'',course,answers,consent,website:f.get('website'),utm:attribution()})});const data=await r.json() as {error?:string,message:string};if(!r.ok)throw new Error(data.error||'We could not save your request. Please try again.');setError(false);setStatus(data.message);}catch(e){setError(true);setStatus(e instanceof Error?e.message:'Something went wrong. Your details are still here; please try again.');}finally{setBusy(false);}}
 return <form className="form" onSubmit={submit}>
 {enrol&&<div className="enrol-summary"><p className="eyebrow">YOUR COURSE ENQUIRY</p><h2>{courses.find(c=>c.slug===course)?.name||'Let’s find your course'}</h2><p>{courses.find(c=>c.slug===course)?'€'+courses.find(c=>c.slug===course)!.price+' · '+courses.find(c=>c.slug===course)!.duration+' · listed course fee':'Select a course below, or ask us to help you choose.'}</p></div>}
 {!report&&<div className="form-row"><div><label htmlFor="lead-name">Your name</label><input id="lead-name" name="name" autoComplete="name" required maxLength={120}/></div><div><label htmlFor="lead-email">Email address</label><input id="lead-email" name="email" type="email" autoComplete="email" required maxLength={254}/></div></div>}
 {report&&<div><label htmlFor="report-email">Email address</label><input id="report-email" name="email" type="email" autoComplete="email" required maxLength={254} placeholder="you@example.com"/></div>}
 {!report&&<><div><label id="course-label">Course you’re considering</label><Select value={course} onValueChange={setCourse}><SelectTrigger className="form-select" aria-labelledby="course-label"><SelectValue/><span className="form-chevron"><LabIcon name="next" size={16}/></span></SelectTrigger><SelectContent><SelectItem value="not-sure">Help me choose</SelectItem>{courses.map(c=><SelectItem key={c.slug} value={c.slug}>{c.name} · €{c.price}</SelectItem>)}</SelectContent></Select></div><div className="form-row"><div><label htmlFor="timezone">City or time zone</label><input id="timezone" name="timezone" placeholder="e.g. Berlin / Europe/Berlin" required maxLength={100}/></div><div><label htmlFor="availability">When are you usually free?</label><input id="availability" name="availability" placeholder="e.g. weekday evenings" required maxLength={200}/></div></div><div><label htmlFor="message">What conversation would you like to handle better? <span className="fine">Optional</span></label><textarea id="message" name="message" maxLength={2000} placeholder="A meeting, an interview, a client call…"/></div></>}
 <div hidden aria-hidden="true"><label>Leave this empty<input name="website" tabIndex={-1} autoComplete="off"/></label></div>
 <div className="consent"><Checkbox id={report?'report-consent':'trial-consent'} checked={consent} onCheckedChange={v=>setConsent(v===true)}/><label htmlFor={report?'report-consent':'trial-consent'}>I agree to the use of my details to {report?'prepare and send my diagnostic report':enrol?'respond to my course enrolment enquiry':'respond to my trial request'}, as described in the <a className="underline" href="/legal/privacy">Privacy Policy</a>. This does not subscribe me to marketing emails.</label></div>
 {report&&storageReady&&!emailReady&&<p className="small">Email delivery is being connected. You can save a report request now; your full result and practice guide are available on this page.</p>}
 {!storageReady&&<p className="note" role="status">Enquiries are not open yet. You can choose your course now and return to this page when enrolment opens. No details have been submitted.</p>}<button className="btn" disabled={busy||!storageReady} type="submit">{busy?'Saving…':report?(emailReady?'Email my personalised report':'Save my report request'):enrol?'Send my enrolment enquiry':'Request my free trial'} <LabIcon name="arrow" size={17}/></button>
 {status&&<p role={error?'alert':'status'} className={'status '+(error?'error':'')}>{status}</p>}
 <p className="fine">{report?'Your result is a reflection tool, not a language qualification.':enrol?'This is an enquiry, not a purchase or recurring subscription. Your course place, final fee and schedule are confirmed separately.':'No payment required. This is a scheduling request; your place and time are confirmed separately.'}</p>
 </form>
}
export function Diagnostic(){const [step,setStep]=useState(0),[answers,setAnswers]=useState<number[]>(Array(7).fill(-1)),[done,setDone]=useState(false),[shareStatus,setShareStatus]=useState('');const heading=useRef<HTMLHeadingElement>(null);useEffect(()=>{if(step>0||done)heading.current?.focus();},[step,done]);const result=scoreDiagnostic(answers);async function share(){const url=ORIGIN+'/diagnostic?result='+result.dimension.slug;try{if(navigator.share)await navigator.share({title:'My plateau: '+result.dimension.name,text:'My Beyond Fluency Lab result: '+result.dimension.name+'. Find your plateau in 90 seconds.',url});else{await navigator.clipboard.writeText(url);setShareStatus('Result link copied.');}}catch(e){if((e as Error).name!=='AbortError')setShareStatus('Copy this result link: '+url);}}
 if(done)return <div className="quiz diagnostic-result"><div className="result-intro"><p className="eyebrow"><LabIcon name="compass" size={26}/> YOUR COMMUNICATION STARTING POINT</p><p className="result-kicker">You’ve found the gap.<br/>Now give it a practice plan.</p><h2 tabIndex={-1} ref={heading}>{result.dimension.name}</h2><h3>{result.dimension.title}</h3><p className="lead">{result.dimension.description}</p></div><CourseInvitation course={result.course} source="diagnostic-result" reason={answers[6]===0?'You chose an upcoming interview. This focused course turns your experience into clear answers and prepares you for the follow-up.':result.course.short}/><details className="result-breakdown"><summary>See how your answers shaped this result</summary><div className="result-score">{dimensions.map((d,i)=><div key={d.slug}><strong>{result.scores[i]} / 6</strong>{d.name}<span className="sr-only"> scenarios selected</span></div>)}</div><p className="small">{result.tied?'Your answers span more than one dimension equally. We used your latest relevant scenario as a starting point. ':'Your most frequently selected friction is the focus above. '}This is a self-reflection tool, not a validated assessment or a measure of ability.</p></details><div className="note"><strong>One thing to practise this week</strong><p style={{marginTop:10}}>{result.dimension.exercise}</p></div><div className="actions"><button className="btn outline" onClick={share}><LabIcon name="share" size={17}/> Share this result</button><button className="text-link" onClick={()=>{setDone(false);setStep(0);setAnswers(Array(7).fill(-1));setShareStatus('');}}>Take it again</button></div>{shareStatus&&<p className="small" role="status">{shareStatus}</p>}<div className="result-report"><h3>Keep your result close.</h3><p className="small" style={{marginBottom:24}}>Get your result, a tailored practice exercise and a related guide in one personalised email.</p><LeadForm report={result} answers={answers}/></div><a className="text-link" href={'/blog/'+result.dimension.guide}>Read your related practice guide <LabIcon name="arrow" size={17}/></a></div>;
 return <div className="quiz"><div className="quiz-top"><span>QUESTION {step+1} OF 7</span><span>Free · No email needed</span></div><Progress value={step/7*100} aria-label={`${step} of 7 questions completed`} className="h-1 rounded-none"/><h2 ref={heading} tabIndex={-1} id="question">{questions[step].q}</h2><p className="small" style={{marginBottom:22}}>Choose the answer closest to your experience. There is no correct answer.</p><RadioGroup aria-labelledby="question" value={answers[step]>=0?String(answers[step]):''} onValueChange={v=>setAnswers(a=>a.map((x,i)=>i===step?Number(v):x))} className="answers">{questions[step].a.map((a,i)=><div className="answer" key={step+'-'+i} onClick={()=>setAnswers(old=>old.map((x,j)=>j===step?i:x))}><RadioGroupItem id={'answer-'+i} value={String(i)}/><label htmlFor={'answer-'+i}>{a}</label></div>)}</RadioGroup><div className="quiz-actions"><button className="btn outline" disabled={step===0} onClick={()=>setStep(step-1)}><LabIcon name="back" size={16}/> Back</button><button className="btn" disabled={answers[step]<0} onClick={()=>step===6?setDone(true):setStep(step+1)}>{step===6?'See my plateau':'Next question'} <LabIcon name="next" size={17}/></button></div></div>
}
export function SharedResult(){const [d,setD]=useState<typeof dimensions[number]|undefined>();useEffect(()=>{const r=new URLSearchParams(location.search).get('result');setD(dimensions.find(x=>x.slug===r));},[]);if(!d)return null;return <aside className="note"><strong>A colleague shared: {d.name}</strong><p>{d.description}</p><p className="small">This describes their result. Take the questions below to find your own.</p></aside>}
